server.port=8082
spring.application.name=business-service

# Base de données — base SÉPARÉE de l'auth-service (principe microservice)
spring.datasource.url=jdbc:mysql://localhost:3306/business_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JWT — DOIT être identique au auth-service pour valider les tokens
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# CORS
cors.allowed-origins=http://localhost:4200,https://votre-app.web.app

logging.level.com.restaurant=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration