server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/business_db
spring.datasource.username=postgres
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

cors.allowed-origins=http://localhost:4200,https://webresto-frontend.onrender.com